name: Build DS Homebrew

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up devkitPro
      run: |
        sudo apt-get update
        sudo apt-get install -y devkitpro

    - name: Build project
      run: |
        make
